// Auto-generated by tools/src/deploy — do not edit manually.
// Regenerate with: npm run deploy
module.exports = {
  apps: [
    {
      name: 'miracle-back',
      script: 'back/dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'miracle-front',
      cwd: './front',
      // Use vite.js directly — PM2 on Windows cannot run npm.cmd as a Node script
      script: '../node_modules/vite/bin/vite.js',
      args: "preview --host --port 8081",
      autorestart: true,
      watch: false,
    },
  ],
};
