import { writeFileSync } from 'fs';
import { resolve } from 'path';
import type { DeployEnv } from '../env.js';
import { info, success } from '../logger.js';

export function genPm2Config(env: DeployEnv, rootDir: string): string {
    const configPath = resolve(rootDir, 'ecosystem.config.cjs');

    const content = `// Auto-generated by tools/src/deploy — do not edit manually.
// Regenerate with: npm run deploy
module.exports = {
  apps: [
    {
      name: 'miracle-back',
      cwd: './back-nest',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'miracle-front',
      cwd: './front',
      // Use vite.js directly — PM2 on Windows cannot run npm.cmd as a Node script
      script: '../node_modules/vite/bin/vite.js',
      args: ${JSON.stringify(`preview --host --port ${env.VITE_PORT}`)},
      autorestart: true,
      watch: false,
    },
  ],
};
`;

    info(`Пишем ecosystem.config.cjs...`);
    writeFileSync(configPath, content, 'utf-8');
    success(`ecosystem.config.cjs создан`);

    return configPath;
}
